file(GLOB_RECURSE ROCKETASM_SOURCES
	"${CMAKE_CURRENT_SOURCE_DIR}/main.c"
	"${CMAKE_CURRENT_SOURCE_DIR}/lexer.h"
	"${CMAKE_CURRENT_SOURCE_DIR}/lexer.c"
	"${CMAKE_CURRENT_SOURCE_DIR}/parser.h"
	"${CMAKE_CURRENT_SOURCE_DIR}/parser.c"
	"${CMAKE_CURRENT_SOURCE_DIR}/program.h"
	"${CMAKE_CURRENT_SOURCE_DIR}/program.c"
	"${CMAKE_CURRENT_SOURCE_DIR}/encoder.h"
	"${CMAKE_CURRENT_SOURCE_DIR}/encoder.c"
	"${CMAKE_CURRENT_SOURCE_DIR}/emitter.h"
	"${CMAKE_CURRENT_SOURCE_DIR}/emitter.c"
)

add_executable(${ROCKETASM_TARGET_NAME} ${ROCKETASM_SOURCES})

set_compile_options_for_target(${ROCKETASM_TARGET_NAME})

target_include_directories(${ROCKETASM_TARGET_NAME} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/../")
 target_link_libraries(${ROCKETASM_TARGET_NAME} PRIVATE ${ROCKETVM_TARGET_NAME})

function(CopyLibToTarget LIB_NAME TARGET_NAME)
	add_custom_command(TARGET ${TARGET_NAME}
		POST_BUILD
		COMMAND
		${CMAKE_COMMAND} -E copy_if_different
		$<TARGET_FILE:${LIB_NAME}>
		$<TARGET_FILE_DIR:${TARGET_NAME}>
	)
endfunction()
